% Load and analyze data from Suite2P files
clear
animal_id = '712';
experiment_day = 'day1';

% Changed in 2019 to 4 ttls per stimulus presentation
n_ttls_per_stim = 4;

% Change this to match the directory that contains the Suite2P mat file you
% want to load and analyze

% Locally in Dropbox
if ismac
    suite_2p_dir = ['~/Dropbox/Salk/GCaMP/GCaMP_Data/', animal_id, '/', experiment_day,...
        '/Suite_2P'];
    
    scanbox_dir = ['~/Dropbox/Salk/GCaMP/GCaMP_Data/', animal_id, '/', experiment_day,...
        '/Scanbox_Files'];
elseif ispc
    suite_2p_dir = ['D:/GCaMP_Data/', animal_id, '/', experiment_day, '/Suite_2P'];
    
    scanbox_dir = ['D:/GCaMP_Data/', animal_id, '/', experiment_day, '/Scanbox_Files'];
end

% % External SSD
% suite_2p_dir = ['/Volumes/EPHYS_000/GCaMP_Data/', animal_id, '/', experiment_day,...
%     '/Suite_2P'];
%  
% scanbox_dir = ['/Volumes/EPHYS_000/GCaMP_Data/', animal_id, '/', experiment_day,...
%     '/Scanbox_Files'];

% % External HDD
% suite_2p_dir = ['/Volumes/2P_Data/Ben/', animal_id, '/', experiment_day,...
%     '/Suite_2P'];
% 
% scanbox_dir = ['/Volumes/2P_Data/Ben/', animal_id, '/', experiment_day,...
%     '/Scanbox_Files'];

% % Sai's Computer
% suite_2p_dir = ['/Volumes/sai/', animal_id, '/', experiment_day,...
%     '/Suite_2P'];
% 
% scanbox_dir = ['/Volumes/sai/', animal_id, '/', experiment_day,...
%     '/Scanbox_Files'];

% Flag to save to Dropbox
dropbox_flag = 'Save to Dropbox? (yes = 1, no = 0)? ';
dropbox_save = input(dropbox_flag);

% Flag to analyze all files in the Scanbox_Files directory
analyze_all_files = 1;

% Flag to turn on/off 5 frame smoothing of fluorescence traces
smooth_traces = 1;

% Flag to turn on/off neuropil subtraction
subtract_neuropil = 1;

% Flag to turn on/off photobleaching decay
photo_bleach_subtract = 0;

cd (suite_2p_dir)
%%
% Get the mat file located in the directory
mat_files = dir('*.mat');
% Check for weird hidden files if the data has been copied from my Mac to
% the external drive
if size(mat_files,1) > 1
    good_mat_files = {};
    file_names = {mat_files(1:end).name};
    for i = 1:length(file_names)
        if contains(file_names{i},'._') == 0
            good_mat_files{end + 1} = file_names{i};
        end
    end
    old_mat_file_name = good_mat_files{1};
else
    old_mat_file_name = mat_files(1).name;
end    
dir_path = mat_files(1).folder;
%%
disp('Loading Suite 2P Data');

% % Load the mat file after renaming
load(old_mat_file_name);

% Finds the rois in the mat file generated by Suite2P are good cells
cell_ids = find(iscell(:,1)>0);

% Get the traces from the rois that are good cells
traces_all = F(cell_ids,:);

% Neuropil subtraction
if subtract_neuropil
    disp('Performing neuropil subtraction');
    traces_all = traces_all - Fneu(cell_ids,:);
end

% smooth traces by mean of 5 frame window.
if smooth_traces
    disp('Smoothing fluorescence traces')
    [traces_all, w] = smoothData(traces_all,2,'movmean',5);
end

% Get list of scanbox files to analyze
cd(scanbox_dir)
sbx_files = dir('*.mat');
% Check for hidden files that begin with '._' and exclude them (Mac OS problem)
good_sbx_files = {};
sbx_file_names = {sbx_files(1:end).name};
for i = 1:length(sbx_file_names)
    if contains(sbx_file_names{i},'._') == 0
        good_sbx_files{end + 1} = sbx_file_names{i};
    end
end
sbx_files = good_sbx_files;
%%
% If you aren't analyzing all the files in the directory, create a pop up
% window to select the file you want to analyze. This doesn't work for
% analyzing a single file anymore, but can be useful for debugging
if ~analyze_all_files
    disp(['Which file are you analyzing?']);
    [file, path] = uigetfile('*.mat');
    files_to_analyze{1} = file;
else
    files_to_analyze = sbx_files;
end

% Before running any analysis, get the size in frames of all the scanbox
% files, sum them, and compare to the size of the fluorescence trace
% imported from the Suite2P mat file.
total_frames = 0;
for i = 1:length(files_to_analyze)
    mat_file = sbx_files{i}(1:end-4);
    sbx_matfile_to_load = [sbx_files{i}(1:end-4),'.mat'];
    load(sbx_matfile_to_load);
    if isfield(info,'max_idx') == 0
        sbxread_bks(mat_file,1,1); % read in sbx mat file and add total_frame to the data structure
        clear info;
        load(sbx_matfile_to_load);
    end
    total_frames = total_frames + (info.max_idx);
end
%%
disp(['Total Frames: ', num2str(total_frames)]);
disp(['Size of Suite2P Traces: ', num2str(length(traces_all))]);
frame_diff = length(traces_all) - total_frames;
mean_frame_diff = floor(frame_diff/length(files_to_analyze));
disp(['Average Frame Offset: ', num2str(mean_frame_diff), ' frames/file']);
prompt = 'Do you want to proceed with the analysis? (yes = 1, no = any key)? ';
proceed = input(prompt);
    
if proceed ~= 1
    return
end

% Loop that does the analysis of each file
for n_file = 1:length(files_to_analyze)
    % cd to the Scanbox_Files directory at the start of each loop
    cd(scanbox_dir);
    file_being_analyzed = files_to_analyze{n_file};
    file = file_being_analyzed;

    % First load the analyzer file to get the duration of the stimulus for
    % use later
    analyzer_file = [file(1:end-4), '.analyzer'];
    analyzer_cell_path = split(pwd,'\');
    analyzer_path = '';
    for t = 1:length(analyzer_cell_path)-1
        analyzer_path = [analyzer_path, analyzer_cell_path{t},'\'];
    end
    analyzer_path = [analyzer_path,'Analyzer_Files'];
    cd(analyzer_path);
    load([analyzer_path, '/',  analyzer_file], '-mat');
    [trial_num, stim_times] = looper_2024([analyzer_path, '/', analyzer_file]);
    
    % Now load the scanbox file
    cd(scanbox_dir);
    disp(['Analyzing: ', file]);
    for i = 1:length(sbx_files)
        fileStr = sbx_files{i};
        if strcmp(fileStr, file)
            nFile = i;
        end
    end
    t_frames = 0;

    % If the file being analyzed isn't the first one in the Suite2P analysis,
    % this code sums the total number of frames that were imaged before the
    % start of the file being analyzed. One frame is subtracted from the total
    % to try to compensate for small timing differences,
    if nFile > 1
        for i = 1:nFile-1
            sbx_matfile_to_load = [sbx_files{i}(1:end-4),'.mat'];
            load(sbx_matfile_to_load);
            t_frames = t_frames + (info.frame(end) + mean_frame_diff);
        end
    end

    % Now load the mat file that corresponds to the file being analyzed and
    % then get the stimulus times, in frames, generated by scanbox
    load([file(1:end-4), '.mat']);

    % Check to see if the frames field in the info data structure has ever
    % been adjusted. If it has, it means there were issues with the ttls
    % generated by scanbox that were fixed manually. When this is done, a
    % new field is added to the info data structure named
    % 'frame_adjusted'. If this field exists, it means any errors have been
    % corrected, so skip this loop and use the 'frame_adjusted' field for
    % the rest of the analysis
    if ~isfield(info,'frame_adjusted')
        % This is to catch weird times where there is an extra ttl thrown
        % somewhere in the scanbox file.
        test_val = length(info.frame);
        if rem(test_val,n_ttls_per_stim)~=0 % the number of stimulus repeats is not divisible by the number of ttls per repeat
            disp('The number of TTLs is not correct. You need to determine why before proceeding.');
            disp('If the first TTL time is not zero, then you need to find the offending TTL and adjust the stim_frames matrix accordingly');
            disp('The script will now pause. Enter dbcont in command window to continue');
            all_ttl_diffs = diff(info.frame); % difference in samples of each TTL
            min_real_ttl = min(stim_times)*15; % fps is actually 15.3, so this generates a minimum integer value that should never exist for a 'real' ttl
            isi_ttls = find(all_ttl_diffs<min_real_ttl); % these should only be inter stimulus intervals/ttls and should be the same size as the number trials presented
            all_isi_ttls_diffs = diff(isi_ttls); % This provides the number of ttls presented between each inter-stim interval. For real sets of ttls, this is match the number of ttls per stimulus (i.e. 4)
            bad_isi_ttls = find(all_isi_ttls_diffs<n_ttls_per_stim);
            bad_ttl_idx = bad_isi_ttls(1)*n_ttls_per_stim;
            tmp_frames = info.frame(1:530); % this is the fix for animal 69, day2_000_001. Your milage may vary...
            tmp_frames = [tmp_frames; tmp_frames(end)+61];
            tmp_frames = [tmp_frames; info.frame(533:end)];
            info.frame_adjusted = tmp_frames;
            keyboard;
            % If you adjusted the ttl times, re-save the info data
            % structure with the new field 'frame_adjusted' added to it
            if isfield(info,'frame_adjusted');
                save([file(1:end-4), '.mat'],'info');
            end
        end
    end

    % If you had to correct the ttl times because of a scanbox error, use
    % the adjusted version of stimulus times for the rest of the analysis
    if isfield(info,'frame_adjusted')
        % Stim times from TTLs generated by scanbox and adjusted manually
        stim_frames = info.frame_adjusted;
    else
         % Stim times from TTLs generated by scanbox
        stim_frames = info.frame;
    end

    % Add the number of frames that have elapsed before the file that is being
    % analyzed occurs so that the stimulus on and off times are shifted to
    % align them with the fluorescence traces.
    stim_frames_shift = stim_frames + t_frames;

    % Get the chunk of the raw fluorescence trace generated by Suite2P that
    % corresponds to the file you are analyzing for all the rois
    % traces_expt = traces_all(:,t_frames + 1:stim_frames(end) + (t_frames + 1));

    % Modification in 2024 because the length of traces_all and the last values
    % of stim_frames sometimes aren't the same. Typically, they are off by only
    % one (1 frame), so the current hack is to add or subtract one from the
    % last value of stim_frames so it matches the length of traces_all.
    if stim_frames(end) + t_frames == length(traces_all)
        traces_expt = traces_all(:,t_frames + 1:stim_frames(end) + t_frames);
    elseif stim_frames(end) + t_frames < length(traces_all)
        traces_expt = traces_all(:,t_frames + 1:stim_frames(end) + (t_frames + 1));
    elseif stim_frames(end) + t_frames > length(traces_all)
        traces_expt = traces_all(:,t_frames + 1:stim_frames(end) + (t_frames - 1));
    end


    fpsRaw = 15;
    % Downsample the frame rate depending on how many planes you are
    % imaging
    if info.volscan~=0
        fps=fpsRaw./info.otparam(3);
    else
        fps = fpsRaw;
    end

    % trial_num is a matrix where each row contains the direction, sf, and
    % tf of each stimulus presented
    n_stim_params = unique(trial_num, 'rows');

    % Get the parameters of the stimuli, including pre/post-stim times as
    % well as stimulus duration
    pre_time = stim_times(1);
    post_time = stim_times(3);
    stim_on_off_times = stim_times(2);

    % Load Spike2 text file automatically (save as spreadsheet text file)
    spike_file = [file(1:end-4), '.txt'];
    spike_cell_path = split(pwd, '\');
    spike_path = '';
    for t = 1:length(spike_cell_path)-1
        spike_path = [spike_path, spike_cell_path{t},'\'];
    end
    spike_path = [spike_path,'Spike2_Files'];
    cd(spike_path);
    opts = detectImportOptions([spike_path, '/', spike_file]);
    stim_info = readtable([spike_path, '/', spike_file],opts);
    stim_info = table2array(stim_info);

    % Voltage signal from photodiode.
    galvo = stim_info(:,6);
    % Voltage signal from one movement encoder
    movt_a = round(stim_info(:,3)./max(stim_info(:,3))); %normalize to binary 0,1
    % Voltage signal from the other movement encoder 
    movt_b = round(stim_info(:,4)./max(stim_info(:,4)));
    % Sample number of the voltage measurements
    t_samp = stim_info(:,1);
    % Voltage signal from the scanbox output indicating start/stop time of
    % visual stimulus
    stim = stim_info(:,5);

    % Determine sampling rate of the digitizer by finding the sample number
    % that corresponds to 1 second.
    fs = find(t_samp == 1)-1;
    fs = fs(1);

    % Create array of times using the calculated sample rate and the total
    % number of samples in the encoder file.
    t_int = (1:size(stim,1)) * fs;

    % %plot to sanity check
    % figure; 
    % subplot(3,1,1); hold all; plot(t_int, galvo,'r'); plot(t_int, stim,'b');
    % subplot(3,1,2); plot(t_int, movt_a);
    % subplot(3,1,3); plot(t_int, movt_b);

    % Set threshold value for determining the start/stop time of each trial
    threshold = 3;
    % Find samples where visual stimulus was above a threshold voltage
    pulses = find(stim>threshold);

    % Find samples where  visual stimulus ended by finding the places where the
    % difference between values in pulses matrix were greater than one.
    down_edges = find(diff(pulses)>1)';
    start_edges = down_edges(1:2:end);
    end_edges = start_edges + 1;

    % Create matrix of start/stop samples for stimulus by sorting the start times
    % and stop times sequentially.
    all_edges = sort([start_edges end_edges]);

    % Times on/off
    on_off = pulses(all_edges);

    % On and off times in samples
    on_times = pulses(start_edges);
    off_times = pulses(end_edges);

    % Duration of stimuli in seconds
    times_s = (off_times-on_times)./fs(1);
    % Duration of inter-trial intervals in seconds
    gap = diff(off_times)./fs(1);

    % Determine which trials were running or stationary. Running if mean speed >0.5 cm/s
    % speed = + = wheel moving forward = backward running, -= wheel moving bw=
    % forward running.

    % Total number of stimuli presented, including blanks
    all_trials = size(trial_num,1);

    % Determine trials during which the mouse was moving at all. Output is a
    % matrix with a binary value for each trial
    [move_trials, all_speeds, mean_speeds] = Intan_digital_movement_HW(all_trials,movt_a, movt_b, [on_times off_times], 0.5,fs); %size(trial_pos,1)

    % Create a matrix that contains all relevant parameters for each
    % stimulus presentation.
    %
    % Col 1: trial start in frames
    % Col 2: stimulus start in frames
    % Col 3: stimulus end in frames
    % Col 4: trial end in frames
    % Col 5: binary value indicating if animal was moving (1 = moving)
    % Col 6: direction of stimulus
    % Col 7: SF of stimulus
    % Col 8: TF of stimulus
    
    trial_info_mat = [stim_frames(1:n_ttls_per_stim:end), stim_frames(2:n_ttls_per_stim:end), stim_frames(3:n_ttls_per_stim:end),...
        stim_frames(4:n_ttls_per_stim:end), move_trials, trial_num];

    % Subtract off photobleaching decay using polynomial fit to the blank trials
    if photo_bleach_subtract == 1

        tracesBlankSub = nan(size(traces_expt));

        % Get the stimulus times that correspond to blank trials
        blankTrialsIndex = find(trial_info_mat(:,6) == 500);
        blankTrials = trial_info_mat(blankTrialsIndex,1:2);

        % Shift back t_frames because the raw trace won't be shifted.
        blankTrials = blankTrials;

        blankXvals = [];

        for i = 1:length(blankTrials)
            blankXvals = [blankXvals, blankTrials(i,1):1:blankTrials(i,2)];
        end

        for i = 1:length(cell_ids)
            % Create matrix the size of the experiment being analyzed in frames
            decayTrace = nan(1,stim_frames(end,1));

            % Get the raw fluorescence trace for the cell being analyzed
            rawCellTrace = traces_expt(i,:);

            for j = 1:length(blankTrials)
                blankRawTrace = rawCellTrace(blankTrials(j,1):blankTrials(j,2));
                decayTrace(blankTrials(j,1):blankTrials(j,2)) = blankRawTrace;

            end

            blankYvalInd = find(~isnan(decayTrace));
            blankYvals = decayTrace(blankYvalInd);
            blankFitVals = polyfit(blankXvals,blankYvals,1);
            fitXvals = (1:1:length(decayTrace) + 1);
            blankFit = blankFitVals(1)*fitXvals + blankFitVals(2);

            rawCellTraceSub = rawCellTrace - blankFit;
            tracesBlankSub(i,:) = rawCellTraceSub;

        end

        traces_expt = tracesBlankSub;
    end


    % Split raw fluorescence traces and calculate dF/F

    % The trial times in frames in the scanbox file don't always produce
    % trials of the exact same number of samples. They seem to alternate by
    % one frame every other trial, so trim all traces to be the smallest
    % trial size.
    min_trial_length = floor(min(trial_info_mat(:,4)-trial_info_mat(:,1)));
    
    % Create NaN array to hold raw fluorescence traces for each trial for each cell
    raw_cell_trials = nan(size(cell_ids,1), size(trial_num,1), min_trial_length);
    
    % Create NaN array to hold dF/F traces for each trial for each cell
    dfof_cell_trials = nan(size(cell_ids,1), size(trial_num,1), min_trial_length);

    % Create NaN array to hold mean and max dF/F during stimulus presentation for each trial for each
    % cell
    mean_dfof_cell_trials = nan(size(cell_ids,1), size(trial_num,1), 1);
    max_dfof_cell_trials = nan(size(cell_ids,1), size(trial_num,1), 1);


    for j = 1:size(cell_ids,1)
        cell_trace = traces_expt(j,:); % fluorescence trace corresponding to the stimulus/experiment being analyzed for the cell being examined from the 

        % Go through each stimulus presentation and cut out the trace aligned
        % with the stimulus start and stop times in frames
        for i = 1:size(trial_info_mat,1)
            % trial start, end, and stimulus start times in frames
            trial_start = trial_info_mat(i,1);
            trial_end = trial_start + (min_trial_length - 1);
            trial_length = trial_end - trial_start;
            stim_start = trial_info_mat(i,2) - trial_info_mat(i,1);
            
            % Trace for trial being examined
            tmp_trace = cell_trace(trial_start:trial_end);
            % Subtract off the minimum value from the trace to eliminate
            % negative values (added in early 2025)
            tmp_trace = tmp_trace - min(tmp_trace);
            % Baseline from trial for dF/F calculation
            tmp_baseline = mean(tmp_trace(1:stim_start));
            % Calculate dF/F
            dfof_trace = (tmp_trace-tmp_baseline)./tmp_baseline;
            % Find max dF/F during stimulus presentation, including post-stim
            max_dfof_trace = max(dfof_trace(stim_start:end));
            % Find mean dF/F during stimulus presentation, including post-stim
            mean_dfof_trace = mean(dfof_trace(stim_start:end));

            % Place values in matrices for later analysis
            raw_cell_trials(j,i,1:size(tmp_trace,2)) = tmp_trace;
            dfof_cell_trials(j,i,1:size(dfof_trace,2)) = dfof_trace;
            mean_dfof_cell_trials(j,i,:) = mean_dfof_trace;
            max_dfof_cell_trials(j,i,:) = max_dfof_trace;

        end

    end
        
    % Create a directory to save the data in
    cd ..
    if isfolder('Analysis') == 0
       mkdir('Analysis')
    end
    cd 'Analysis'

    disp(['Saving files'])

    % Clear the old data structure if it exists
    if exist('gcamp_data','var')
        clear gcamp_data;
    end
    gcamp_data(length(cell_ids)) = struct();

    % Create the data structure
    % Cell IDs
    gcamp_data(1).cell_ids = [];
    % Dfof trace for each trial presented for each cell. Each entry (row) will
    % be m x n matrix, where m = number of trials and n = the dfof trace
    % for that trial
    gcamp_data(1).dfof_traces = [];
    % matrix of mean dfofs for all trials for each cell
    gcamp_data(1).mean_dfof_resp = [];
    % matrix of max dfof for all trials for each cell
    gcamp_data(1).max_dfof_resp = [];

    % Loop through the list of cells and put data in the structure
    for i = 1:length(cell_ids)
        gcamp_data(i).cell_ids = cell_ids(i);
        gcamp_data(i).dfof_traces = squeeze(dfof_cell_trials(i,:,:));
        gcamp_data(i).mean_dfof_resp = squeeze(mean_dfof_cell_trials(i,:,:));
        gcamp_data(i).max_dfof_resp = squeeze(max_dfof_cell_trials(i,:,:));
    end
    
    % % Get maximum mean fluorescence of all ROIs. This was a threshold
    % % Helen used that I abandoned in early 2025
    % all_mean_dfof = [];
    % all_mean_dfof = [all_mean_dfof, gcamp_data(1,:).mean_dfof_resp];
    % max_mean_dfof = max(all_mean_dfof);
    % fluor_thresh = max_mean_dfof * 0.06;
    % 
    % for i = 1:size(gcamp_data,2)
    %     max_roi_mean_dfof = max(gcamp_data(i).mean_dfof_resp);
    %     if max_roi_mean_dfof <= fluor_thresh
    %         gcamp_data(i).good_fluor = 0; % not reliable, too low
    %     else
    %         gcamp_data(i).good_fluor = 1; % reliable, above threshold
    %     end
    % end


    % Stimulus conditions for each trial presented. This is a matrix that
    % contains (by column) the stimulus pre, start, stop, and post times (in frames), a
    % binary value indicating whether the animal was moving, then the various
    % stimulus conditions for each trial of the stimulus

    % Also save out the matrix that contains the stimulus conditions for each
    % trial presented. This is a matrix that contains (by column) the (1) pre,
    % (2) start, (3) stop, and (4) post stim times, (5) a binary value indicating
    % whether the animal was moving, then the parameters of the visual stimulus
    % that was presented in the following order: (6) orientation, (7) spatial
    % frequency, (8) temporal frequency.

    stimulus_info = trial_info_mat;

    % Save locally
    save([file(1:end-4), '_Data'], 'gcamp_data', 'stimulus_info');
    
    % Save to Dropbox
    if dropbox_save == 1
        if ismac
            cd ~/Dropbox/Salk/GCaMP/Data/
        elseif ispc
            cd C:/Users/SNLC_BS_PC/Dropbox/Salk/GCaMP/Data
        end
        if isfolder(animal_id) == 0
            mkdir(animal_id)
        end
        cd(animal_id)
        if isfolder(experiment_day) == 0
            mkdir(experiment_day)
        end
        cd(experiment_day)
        if isfolder('Analysis') == 0
            mkdir('Analysis')
        end
        cd('Analysis')
    end
    save([file(1:end-4), '_Data'], 'gcamp_data', 'stimulus_info');
end


